name: UNCSURVIVAL
version: '${project.version}'
main: teamunc.uncsurvival.UNCSurvival
api-version: 1.18
authors: [ Delsus ]
description: UNCSURVIVAL PRIVATE PLUGIN
website: team-unc.fr

commands:
  startuncsurvival:
    description: Start the game
    usage: /startuncsurvival
    permission: uncsurvival.startuncsurvival
  addplayer:
    description: Add players to the game
    usage: /addplayer <playerName> <playerName?> ...
    permission: uncsurvival.addplayer
  removeplayer:
    description: Remove players from the game
    usage: /removeplayer <playerName> <playerName?> ...
    permission: uncsurvival.removeplayer

  addplayertoteam:
    description: Add players to a team
    usage: /addplayertoteam <TeamColor> <ParticipantplayerName> <ParticipantplayerName?> ...
    permission: uncsurvival.addplayertoteam
  removeplayertoteam:
    description: Remove players from a team
    usage: /removeplayertoteam <TeamColor> <ParticipantplayerName> <ParticipantplayerName?> ...
    permission: uncsurvival.removeplayertoteam

  addteam:
    description: Add a Team
    usage: must be a player to execute this command.
      Actual location = spawnpoint and center of the team
      /addteam <TeamName> <TeamColor>
    permission: uncsurvival.addteam

  removeteam:
    description: Remove a team
    usage: /removeteam <TeamName>
    permission: uncsurvival.removeteam

  getplayersingame:
    description: get players in the game
    usage: /getplayersingame
    permission: uncsurvival.getplayersingame

  givediamondapple:
    description: give a diamond apple
    usage: /givediamondapple
    permission: uncsurvival.giveDiamondApple