name: UNCSurvival
version: '${project.version}'
main: teamunc.uncsurvival.UNCSurvival
api-version: 1.18
authors: [ Delsus ]
description: UNCSURVIVAL PRIVATE PLUGIN
website: team-unc.fr

commands:
  startuncsurvival:
    description: Start the game
    usage: /startuncsurvival
    permission: uncsurvival.startuncsurvival

  addplayertoteam:
    description: Add players to a team
    usage: /addplayertoteam <TeamColor> <ParticipantplayerName> <ParticipantplayerName?> ...
    permission: uncsurvival.addplayertoteam
  removeplayertoteam:
    description: Remove players from a team
    usage: /removeplayertoteam <TeamColor> <ParticipantplayerName> <ParticipantplayerName?> ...
    permission: uncsurvival.removeplayertoteam

  addteam:
    description: Add a Team
    usage: must be a player to execute this command.
      Actual location = spawnpoint and center of the team
      /addteam <TeamName> <TeamColor>
    permission: uncsurvival.addteam

  nextphase:
    description: Go to next phase
    usage: /nextphase
    permission: uncsurival.nextphase

  addtime:
    description: Add time to timer
    usage: Use /addtime [secondes] [minutes] [hours] [day]
    permission: uncsurvival.addtime

  removetime:
    description: Remove time to timer
    usage: Use /removetime [secondes] [minutes] [hours] [day]
    permission: uncsurvival.addtime

  removeteam:
    description: Remove a team
    usage: /removeteam <TeamName>
    permission: uncsurvival.removeteam

  getplayersingame:
    description: get players in the game
    usage: /getplayersingame
    permission: uncsurvival.getplayersingame

  givecustomitem:
    description: give a custom item
    usage: /givecustomitem
    permission: uncsurvival.giveCustomItem

  reloadconfig:
    description: reload configuration
    usage: /reloadconfig
    permission: uncsurvival.reloadconfig