name: UNCSurvival
version: '${project.version}'
main: teamunc.uncsurvival.UNCSurvival
api-version: 1.18
authors: [ Delsus ]
description: UNCSURVIVAL PRIVATE PLUGIN
website: team-unc.fr

commands:
  startuncsurvival:
    description: Start the game
    usage: /startuncsurvival
    permission: uncsurvival.admins

  addplayertoteam:
    description: Add players to a team
    usage: /addplayertoteam <TeamColor> <ParticipantplayerName> <ParticipantplayerName?> ...
    permission: uncsurvival.admins
  removeplayertoteam:
    description: Remove players from a team
    usage: /removeplayertoteam <TeamColor> <ParticipantplayerName> <ParticipantplayerName?> ...
    permission: uncsurvival.admins

  addteam:
    description: Add a Team
    usage: must be a player to execute this command.
      Actual location = spawnpoint and center of the team
      /addteam <TeamName> <TeamColor>
    permission: uncsurvival.admins

  nextphase:
    description: Go to next phase
    usage: /nextphase
    permission: uncsurvival.admins

  addtime:
    description: Add time to timer
    usage: Use /addtime [secondes] [minutes] [hours] [day]
    permission: uncsurvival.admins

  removetime:
    description: Remove time to timer
    usage: Use /removetime [secondes] [minutes] [hours] [day]
    permission: uncsurvival.admins

  removeteam:
    description: Remove a team
    usage: /removeteam <TeamName>
    permission: uncsurvival.admins

  getplayersingame:
    description: get players in the game
    usage: /getplayersingame
    permission: uncsurvival.admins

  stats:
    description: get stats for your team
    usage: /stats
    permission: uncsurvival.player

  statsteam:
    description: get stats for your team
    usage: /stats <team>
    permission: uncsurvival.admins

  classement:
    description: get leaderboard
    usage: /classement
    permission: uncsurvival.player

  phaseinfo:
    description: get phases info
    usage: /phaseinfo
    permission: uncsurvival.player

  givecustomitem:
    description: give a custom item
    usage: /givecustomitem
    permission: uncsurvival.admins

  reloadconfig:
    description: reload configuration
    usage: /reloadconfig
    permission: uncsurvival.admins

  addBonusscore:
    description: add a bonus score to a team
    usage: /addbonusscore <TeamColor> <score>
    permission: uncsurvival.admins

  removebonusscore:
    description: remove a bonus score to a team
    usage: /removebonusscore <TeamColor> <score>
    permission: uncsurvival.admins

  addscore:
    description: add a fix number to the score of a team
    usage: /addscore <TeamColor> <score>
    permission: uncsurvival.admins

  removescore:
    description: remove a fix number to the score of a team
    usage: /removescore <TeamColor> <score>
    permission: uncsurvival.admins

  food:
    description: get stats of your food history
    usage: /food
    permission: uncsurvival.player
  f:
    description: get stats of your food history
    usage: /f
    permission: uncsurvival.player

  achievements:
    description: get all achievements of the uncSurvival
    usage: /achievements
    permission: uncsurvival.player

  startduel:
    description: start a duel with two players
    usage: /duel player1 player2
    permission: uncsurvival.admins

  modifyitemvalue:
    description: modify value of an item goal
    usage: /modifyitemvalue <item number> <value>
    permission: uncsurvival.admins

  modifyitemnumber:
    description: modify value of an item goal
    usage: /modifyitemnumber <team> <item number> <newValue>
    permission: uncsurvival.admins

  openinv:
      description: Open inventory of a player
      usage: /openinv <Player>
      permission: uncsurvival.admins
  openenderchest:
    description: Open ender chest of a player
    usage: /openenderchest <Player>
    permission: uncsurvival.admins

permissions:
  uncsurvival.admins:
      default: op
  uncsurvival.player:
      default: true