name: UNCSURVIVAL
version: '${project.version}'
main: teamunc.uncsurvival.UNCSurvival
api-version: 1.18
authors: [ Delsus ]
description: UNCSURVIVAL PRIVATE PLUGIN
website: team-unc.fr

commands:
  startuncsurvival:
    description: Start the game
    usage: /startuncsurvival
    permission: uncsurvival.startuncsurvival
  addplayer:
    description: Add players to the game
    usage: /addplayer <playerName> <playerName?> ...
    permission: uncsurvival.addplayer
  removeplayer:
    description: Remove players from the game
    usage: /removeplayer <playerName> <playerName?> ...
    permission: uncsurvival.removeplayer
  getplayersingame:
    description: get players in the game
    usage: /getplayersingame
    permission: uncsurvival.getplayersingame

  givediamondapple:
    description: give a diamond apple
    usage: /givediamondapple
    permission: uncsurvival.giveDiamondApple